# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    container_name: pool-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 43306:3306
    environment:
      MYSQL_DATABASE: pooldb
      MYSQL_ROOT_PASSWORD: p4ssw0rd
